# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_propiedad_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='estado_negocio',
            field=models.CharField(blank=True, choices=[('PARA RENTA', 'PARA RENTA'), ('PARA VENTA', 'PARA RENTA')], max_length=65, null=True),
        ),
    ]
