# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0005_propiedad_estado_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='galerias',
            field=models.ManyToManyField(null=True, to='realstate.Galeria'),
        ),
    ]
