# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0006_auto_20170203_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='estado_negocio',
            field=models.CharField(blank=True, choices=[('PARA RENTA', 'PARA RENTA'), ('PARA VENTA', 'PARA VENTA')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='galerias',
            field=models.ManyToManyField(blank=True, null=True, to='realstate.Galeria'),
        ),
    ]
