# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0007_auto_20170203_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(default=23500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
