# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import realstate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0008_auto_20170203_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='portada',
            field=models.ImageField(null=True, upload_to=realstate.models.get_media_url),
        ),
    ]
