# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import realstate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0009_auto_20170204_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=realstate.models.get_media_url),
        ),
    ]
