# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0011_auto_20170204_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='galeria',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fotos',
        ),
        migrations.AddField(
            model_name='foto',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.TextField(max_length=500),
        ),
    ]
